name: Checks
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: security
          python-version: 3.9
        - name: flake8
          python-version: 3.9
        - name: pylint
          python-version: 3.9
        - name: docs
          python-version: 3.8  # Keep in sync with .readthedocs.yml

    steps:
    - uses: actions/checkout@v2

    - name: Install system libraries
      if: matrix.system-libraries
      run: |
        sudo apt-get update
        sudo apt-get install ${{ join(matrix.system-libraries, ' ') }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run check
      env:
        TOXENV: ${{ matrix.name }}
      run: |
        pip install -U tox
        tox
